-- The AI agent: per-property settings, the knowledge index it answers from, and the record of
-- every turn. See docs/AI_AGENT.md.

-- pgvector. The postgres image is built with it (infrastructure/docker/postgres.Dockerfile);
-- a database that was initialised before this migration gets the extension here.
CREATE EXTENSION IF NOT EXISTS "vector";

-- CreateEnum
CREATE TYPE "AiMode" AS ENUM ('team', 'ai_when_offline', 'ai');

-- CreateEnum
CREATE TYPE "KnowledgeDocumentKind" AS ENUM ('article', 'notes');

-- CreateEnum
CREATE TYPE "AiDecision" AS ENUM ('answer', 'ticket', 'human', 'failed');

-- CreateEnum
CREATE TYPE "AiProviderKind" AS ENUM ('local', 'openai', 'deepseek');

-- AlterTable
ALTER TABLE "conversations" ADD COLUMN     "ai_handoff_at" TIMESTAMPTZ(6),
ADD COLUMN     "ai_last_reply_at" TIMESTAMPTZ(6),
ADD COLUMN     "ai_paused_at" TIMESTAMPTZ(6),
ADD COLUMN     "ai_reply_count" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "plans" ADD COLUMN     "ai_replies_per_month" INTEGER;

-- Every plan starts unlimited (NULL): the operator's decision is that AI replies are not capped.
-- The column exists so a cap can be set per plan from the console if that ever changes.

-- CreateTable
CREATE TABLE "ai_settings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "account_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "mode" "AiMode" NOT NULL DEFAULT 'team',
    "assistant_name" TEXT NOT NULL DEFAULT 'AI assistant',
    "instructions" TEXT NOT NULL DEFAULT '',
    "key_facts" TEXT NOT NULL DEFAULT '',
    "ticket_offer_text" TEXT NOT NULL DEFAULT 'I can''t help with that from here, but our team can. Would you like me to open a support ticket so they can follow up by email?',
    "handoff_text" TEXT NOT NULL DEFAULT 'I''m passing this to a member of our team - they''ll pick it up right here in a moment.',
    "max_replies_per_conversation" INTEGER NOT NULL DEFAULT 50,
    "enabled_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "ai_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "knowledge_documents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "account_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "kind" "KnowledgeDocumentKind" NOT NULL,
    "article_id" UUID,
    "title" TEXT NOT NULL,
    "url" TEXT,
    "text" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL,
    "token_count" INTEGER NOT NULL DEFAULT 0,
    "chunk_count" INTEGER NOT NULL DEFAULT 0,
    "indexed_at" TIMESTAMPTZ(6),
    "error" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "knowledge_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- `search` is generated by the database from the text. The 'simple' configuration is deliberate:
-- it does no language stemming, so it treats Bangla, English and a product code the same way,
-- and the vector side of retrieval carries the meaning.
CREATE TABLE "knowledge_chunks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "account_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "document_id" UUID NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "heading" TEXT,
    "text" TEXT NOT NULL,
    "token_count" INTEGER NOT NULL DEFAULT 0,
    "embedding" vector(768) NOT NULL,
    "search" tsvector NOT NULL GENERATED ALWAYS AS (to_tsvector('simple', coalesce("heading", '') || ' ' || "text")) STORED,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "knowledge_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_turns" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "account_id" UUID NOT NULL,
    "property_id" UUID NOT NULL,
    "conversation_id" UUID NOT NULL,
    "visitor_message_id" UUID NOT NULL,
    "reply_message_id" UUID,
    "decision" "AiDecision" NOT NULL,
    "provider" "AiProviderKind",
    "model" TEXT,
    "fell_back" BOOLEAN NOT NULL DEFAULT false,
    "prompt_tokens" INTEGER NOT NULL DEFAULT 0,
    "completion_tokens" INTEGER NOT NULL DEFAULT 0,
    "latency_ms" INTEGER NOT NULL DEFAULT 0,
    "retrieved_chunk_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "cited_chunk_ids" UUID[] DEFAULT ARRAY[]::UUID[],
    "error" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_turns_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ai_settings_account_id_id_key" ON "ai_settings"("account_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "ai_settings_account_id_property_id_key" ON "ai_settings"("account_id", "property_id");

-- CreateIndex
CREATE INDEX "knowledge_documents_account_id_property_id_kind_idx" ON "knowledge_documents"("account_id", "property_id", "kind");

-- CreateIndex
CREATE UNIQUE INDEX "knowledge_documents_account_id_id_key" ON "knowledge_documents"("account_id", "id");

-- CreateIndex
CREATE UNIQUE INDEX "knowledge_documents_account_id_article_id_key" ON "knowledge_documents"("account_id", "article_id");

-- CreateIndex
CREATE INDEX "knowledge_chunks_account_id_property_id_idx" ON "knowledge_chunks"("account_id", "property_id");

-- CreateIndex
CREATE UNIQUE INDEX "knowledge_chunks_document_id_ordinal_key" ON "knowledge_chunks"("document_id", "ordinal");

-- Retrieval. HNSW over cosine distance for the vector half; GIN over the tsvector for the
-- full-text half. Every query filters by account and property before either index is consulted.
CREATE INDEX "knowledge_chunks_embedding_idx" ON "knowledge_chunks" USING hnsw ("embedding" vector_cosine_ops);
CREATE INDEX "knowledge_chunks_search_idx" ON "knowledge_chunks" USING GIN ("search");

-- CreateIndex
CREATE INDEX "ai_turns_account_id_created_at_idx" ON "ai_turns"("account_id", "created_at" DESC);

-- CreateIndex
CREATE INDEX "ai_turns_conversation_id_created_at_idx" ON "ai_turns"("conversation_id", "created_at");

-- AddForeignKey
ALTER TABLE "ai_settings" ADD CONSTRAINT "ai_settings_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_settings" ADD CONSTRAINT "ai_settings_account_id_property_id_fkey" FOREIGN KEY ("account_id", "property_id") REFERENCES "properties"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "knowledge_documents" ADD CONSTRAINT "knowledge_documents_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "knowledge_documents" ADD CONSTRAINT "knowledge_documents_account_id_property_id_fkey" FOREIGN KEY ("account_id", "property_id") REFERENCES "properties"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "knowledge_documents" ADD CONSTRAINT "knowledge_documents_account_id_article_id_fkey" FOREIGN KEY ("account_id", "article_id") REFERENCES "kb_articles"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "knowledge_chunks_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "knowledge_chunks_account_id_document_id_fkey" FOREIGN KEY ("account_id", "document_id") REFERENCES "knowledge_documents"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_turns" ADD CONSTRAINT "ai_turns_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_turns" ADD CONSTRAINT "ai_turns_account_id_property_id_fkey" FOREIGN KEY ("account_id", "property_id") REFERENCES "properties"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_turns" ADD CONSTRAINT "ai_turns_account_id_conversation_id_fkey" FOREIGN KEY ("account_id", "conversation_id") REFERENCES "conversations"("account_id", "id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Managing the AI agent is a property-level concern: the people who can change the widget can
-- change its assistant. Owners and admins already hold every permission.
UPDATE "roles"
SET "permissions" = array_append("permissions", 'ai:manage')
WHERE "key" IN ('owner', 'admin', 'manager')
  AND NOT ('ai:manage' = ANY("permissions"));

-- The operator side: provider keys, usage.
UPDATE "platform_admins"
SET "permissions" = array_append("permissions", 'platform:ai:manage')
WHERE NOT ('platform:ai:manage' = ANY("permissions"));
