import type { Message } from '@smartchat/database';
import { RedisChannel, ServerEvent } from '@smartchat/types';
import type { RedisClient } from '../redis/client.js';

/**
 * Domain events, published to Redis and fanned out to sockets by the realtime gateway.
 *
 * The API and the gateway both publish here rather than one calling the other. That is what makes
 * the two paths identical: a message sent over HTTP reaches connected clients by exactly the same
 * route as one sent over the socket, so they cannot behave differently.
 */

export interface MessageDto {
  id: string;
  conversationId: string;
  seq: number;
  clientMessageId: string | null;
  senderType: 'visitor' | 'agent' | 'system' | 'bot';
  senderId: string | null;
  senderName: string | null;
  type: 'text' | 'file' | 'image' | 'system' | 'note';
  body: string;
  createdAt: string;
  readAt: string | null;
  /**
   * The file this message is, when it is a file.
   *
   * Carried inline rather than looked up by the client: a message and its attachment arrive
   * together over the socket, so a bubble never renders as an empty box waiting for a second
   * request that may not come.
   */
  attachment?: MessageAttachment;
  /**
   * Structured detail for a system message, so clients can render their own wording instead of
   * displaying whatever English happened to be written into `body` when the row was created.
   *
   * Only present on `type: 'system'` messages, which are generated by this service and contain
   * nothing a client did not already have. Every other message type omits it, because message
   * metadata is an internal bag and must not leak by default.
   */
  event?: SystemMessageEvent;
  /**
   * Present on bot messages the AI agent wrote: where the answer came from, and whether the
   * message carries the ticket offer. Whitelisted out of the metadata bag like `event`.
   */
  ai?: AiMessageInfo;
}

export interface AiMessageInfo {
  /** The documents the reply was answered from, in rank order. Empty for an offer or a handoff. */
  sources: Array<{ title: string; url: string | null }>;
  /** The widget shows "Create a ticket" / "Ask something else" under a message that offers one. */
  offer?: 'ticket';
}

/** Narrow a stored metadata bag to the AI-message shape, or nothing if it is not one. */
function readAiInfo(message: MessageMaybeWithSender): AiMessageInfo | undefined {
  if (message.senderType !== 'bot') return undefined;
  const raw = message.metadata as Record<string, unknown> | null;
  if (raw?.['source'] !== 'ai') return undefined;
  const sources: AiMessageInfo['sources'] = [];
  if (Array.isArray(raw['sources'])) {
    for (const entry of raw['sources']) {
      if (!entry || typeof entry !== 'object') continue;
      const title = (entry as Record<string, unknown>)['title'];
      const url = (entry as Record<string, unknown>)['url'];
      if (typeof title !== 'string') continue;
      sources.push({ title, url: typeof url === 'string' ? url : null });
    }
  }
  return { sources, ...(raw['offer'] === 'ticket' ? { offer: 'ticket' as const } : {}) };
}

/**
 * What a client needs to render an attachment.
 *
 * Deliberately not the storage key, and deliberately not a URL. A download URL is short-lived and
 * is minted per request against the caller's own permission, so putting one in a transcript would
 * mean either a dead link or a live one that outlives the reader's access.
 */
export interface MessageAttachment {
  id: string;
  fileName: string;
  contentType: string;
  byteSize: number;
  isImage: boolean;
  width: number | null;
  height: number | null;
}

/** What a system message records. `body` is the human-readable fallback for exports. */
export interface SystemMessageEvent {
  kind: 'conversation.closed' | 'conversation.reopened';
  /** Who did it. `visitor` is the person in the widget; `agent` is a member of the account. */
  by: 'visitor' | 'agent';
  /** The agent's display name when an agent did it, so the transcript reads naturally. */
  actorName?: string;
}

/** Narrow a stored metadata bag to the system-message shape, or nothing if it is not one. */
function readSystemEvent(message: MessageMaybeWithSender): SystemMessageEvent | undefined {
  if (message.type !== 'system') return undefined;
  const raw = message.metadata as Record<string, unknown> | null;
  const kind = raw?.['kind'];
  const by = raw?.['by'];
  if (kind !== 'conversation.closed' && kind !== 'conversation.reopened') return undefined;
  if (by !== 'visitor' && by !== 'agent') return undefined;
  const actorName = raw?.['actorName'];
  return {
    kind,
    by,
    ...(typeof actorName === 'string' && actorName.length > 0 ? { actorName } : {}),
  };
}

/** A message that may carry the sender relation, so history can attribute itself. */
type MessageMaybeWithSender = Message & {
  sender?: { displayName: string | null; user: { name: string } | null } | null;
};

export function toMessageDto(
  message: MessageMaybeWithSender,
  senderName?: string | null,
  attachment?: MessageAttachment | undefined,
): MessageDto {
  // The caller's name wins (it is the live sender's own context); otherwise fall back to the
  // relation, which is what makes a reloaded transcript read the same as the live one. A bot has
  // no relation, so its name travels in the metadata it was written with.
  const botName =
    message.senderType === 'bot'
      ? (message.metadata as Record<string, unknown> | null)?.['senderName']
      : undefined;
  const resolvedName =
    senderName ??
    message.sender?.displayName ??
    message.sender?.user?.name ??
    (typeof botName === 'string' && botName.length > 0 ? botName : null);

  return {
    id: message.id,
    conversationId: message.conversationId,
    // BigInt does not survive JSON. Sequence numbers stay far below Number.MAX_SAFE_INTEGER
    // (9×10^15 messages in one conversation), so a number is safe and far easier to work with.
    seq: Number(message.seq),
    clientMessageId: message.clientMessageId,
    senderType: message.senderType,
    senderId: message.senderMemberId ?? message.senderVisitorId,
    senderName: resolvedName,
    type: message.type,
    body: message.body,
    createdAt: message.createdAt.toISOString(),
    readAt: message.readAt?.toISOString() ?? null,
    ...(attachment ? { attachment } : {}),
    ...(() => {
      const event = readSystemEvent(message);
      return event ? { event } : {};
    })(),
    ...(() => {
      const ai = readAiInfo(message);
      return ai ? { ai } : {};
    })(),
  };
}

export interface DomainEvent {
  type: ServerEvent;
  accountId: string;
  propertyId: string;
  conversationId?: string;
  visitorId?: string;
  /**
   * When true the event carries content a visitor must never see (an internal note, agent-only
   * metadata) and is delivered to agent rooms only.
   */
  agentsOnly?: boolean;
  payload: Record<string, unknown>;
  /** Correlates the event back to the request that produced it. */
  requestId?: string;
}

export interface EventPublisher {
  publish(event: DomainEvent): Promise<void>;
}

/** Publishes to Redis so every gateway instance can deliver to its own connected sockets. */
export class RedisEventPublisher implements EventPublisher {
  constructor(
    private readonly redis: RedisClient,
    private readonly onError?: (error: Error) => void,
  ) {}

  async publish(event: DomainEvent): Promise<void> {
    try {
      await this.redis.publish(RedisChannel.CONVERSATION_EVENTS, JSON.stringify(event));
    } catch (error) {
      // A failed broadcast must never fail the write that produced it: the message is already
      // durable in Postgres, and clients recover it on their next sync.
      this.onError?.(error as Error);
    }
  }
}

export { ServerEvent };

/**
 * Availability, broadcast the moment somebody changes it.
 *
 * A separate channel from conversation events because it is a different shape and a different
 * audience: no conversation, no property, one flag for every visitor of an account.
 *
 * It exists because the dashboard's availability control speaks HTTP to the API, while the sockets
 * that have to hear about the change live in the realtime gateway — a different process. Without
 * this, changing your status updated a database row and nothing else: every widget already open
 * kept whatever it was told at bootstrap, indefinitely.
 */
export interface AvailabilityEvent {
  accountId: string;
  available: boolean;
}

export interface AvailabilityPublisher {
  publishAvailability(event: AvailabilityEvent): Promise<void>;
}

export class RedisAvailabilityPublisher implements AvailabilityPublisher {
  constructor(
    private readonly redis: RedisClient,
    private readonly onError?: (error: Error) => void,
  ) {}

  async publishAvailability(event: AvailabilityEvent): Promise<void> {
    try {
      await this.redis.publish(RedisChannel.PRESENCE_EVENTS, JSON.stringify(event));
    } catch (error) {
      // Never fail the status change over a failed broadcast: the choice is already saved, and a
      // widget that missed the announcement gets the right answer on its next bootstrap.
      this.onError?.(error as Error);
    }
  }
}
